### ISSUE TITLE
Blob data dumps are useless

### ISSUE THREAD

**Issue by Alessy** [assignar/mysqldump#7]
In MySQL database, I have longblob data. When I make the dump, data become useless. I can't even execute these statements. What is the point of SchemaDumpOptions.format option?

**Comment by bradzacher** [comment]
The `SchemaDumpOptions.format` options is there to turn the sql formatter on or off.
This is not so useful when just dumping `CREATE TABLE` statements, as those are generated formatted by the DB itself.
However the `INSERT` statements are built within this library, so it will format those.
Additionally if you have any `TRIGGERS`, then it will format them consistently.

-------------

Could you give me an example of the dump you're getting for the `LONGBLOB`?


The `[TINY/MEDIUM/LONG]BLOB` types should be exported in a hexadecimal format. I.e
https://github.com/assignar/mysqldump/blob/6c6ed7f/test/fixtures/data.sql#L194-L220
```
    X'1234',
    X'4321',
    X'ff',
    X'abc123',
```

Is this not the case?
This data inserts fine into my databases.

**Comment by Alessy** [comment]
I noticed that from query SELECT * FROM table I get buffer where values are 9, A, D instead of 09, 0A, 0D
leading zeros are removed.

instead of 
X'52450939393909310933303009555344095745423030303030303030323309574542303030303030303032330D0A393939093938370955534409343538093330300932322E30362E323031380909555609333030090909090932382E30362E32303138090909090909090909090936095409097465737420746573742032096D616A617320320909300932322E30362E3230313809323030093130300909090909090909090909090909090909090D0A

I get

X'5245939393993193330309555344957454230303030303030303233957454230303030303030303233da3939399393837955534493435389333030932322e30362e3230313899555693330309999932382e30362e32303138999999999993695499746573742074657374203296d616a617320329930932322e30362e3230313893230309313030999999999999999999da

**Comment by bradzacher** [comment]
I see the bug!

the blobs get converted from a buffer to a hex string 1 byte at a time.
However 1-byte int should always be 2 hex characters long.
I used `toString(16)` which doesn't zero-pad the output.

I'll push a fix out for it asap.

**Comment by Alessy** [comment]
Thanks for the quick fix.
