### ISSUE TITLE
Handle Table relationships

### ISSUE THREAD

**Issue by aldofunes** [assignar/mysqldump#8]
Can we push the relationships (FKs) to the bottom of the schema dump?

If I run the resulting script on an empty DB, i get errors for tables that do not exist during FK definition.

A much more elegant approach would be to sort the declarations according to their relationships (if they have one)

Any comments on this?

BTW, if you point me in the right direction, I can help you and submit a PR.

**Comment by aldofunes** [comment]
I'm thinking maybe a `.sort()` and checking if the statement contains the string `FOREIGN KEY` and sending them to the bottom.

**Comment by aldofunes** [comment]
Or maybe a simple extraction of `CONSTRAINT fk_someKey FOREIGN KEY` and make a second array with it

**Comment by bradzacher** [comment]
What version of MySQL are you on?

In the header of the dumped file, before any statements, it should be placing some global session variables:
https://github.com/assignar/mysqldump/blob/v2/src/sessionVariables.ts

With the important line being:
```SQL
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
```

This should disable foreign key checks completely until the footer turns them back on:
```SQL
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
```

If you run the dumped SQL file at once (i.e. via (mysql2)[https://github.com/sidorares/node-mysql2]), or via something like SequelPro's import function), then it should execute all the statements within one session and hence work fine.

For example, here is roughly the `mysql2` code we use to clone a DB from the cloud to our local dev environment:
```TS
async function createEmptyDb() {
    const pool = mysql.createPool({
        user: config.rds.username,
        password: config.rds.password,
        port: config.rds.port,
        host: 'db-url.example.com',
        // note we don't set a database here!
        multipleStatements: true,
    })
    console.info('Nuking existing DB')
    const connection = await pool.getConnection()
    await connection.query(`DROP DATABASE IF EXISTS ${dbName}`)
    console.info('Creating clean DB')
    await connection.query(`CREATE DATABASE IF NOT EXISTS ${dbName}`)
    connection.release()
    pool.end().catch(() => {})
}

async function fillDb() {
    // switch to it and load the schema into the db
    console.info('Loading Dump into DB')
    const pool = mysql.createPool({
        user: config.rds.username,
        password: config.rds.password,
        port: config.rds.port,
        host: 'db-url.example.com',
        database: dbName,
        multipleStatements: true,
    })
    const connection = await pool.getConnection()
    await connection.query(dump)
    connection.release()
    pool.end().catch(() => {})
}
```

**Comment by aldofunes** [comment]
I am using MySQL@5.7

I see now. I was returning from function and into a string. This way, the session variables are not included. Only when streaming directly to file. I switched to this pattern and it works fine now.

I guess it is just a thing with the value being returned instead of streamed

**Comment by bradzacher** [comment]
it's a difficult thing to do to separate out the foreign keys.

The way we get the create table statements is via `SHOW CREATE TABLE tablename`.
So for us to split out the foreign keys to remove the need for turning off foreign key checks would be a bit of work.

I think mysql provides access to the column metadata via certain global tables, but we'd have to hand craft the create statements.


It would probably be good to at least provide access to the header flags so you can do this without streaming to a file.

**Comment by bradzacher** [comment]
hi @aldofunes - we've been given control of the proper `mysqldump` repository.
as such this repository is being renamed and archived.

I've moved the latter part of your issue (adding variables to the return value) to  https://github.com/bradzacher/mysqldump/issues/48
